// SPDX-FileCopyrightText: Copyright (C) Arduino s.r.l. and/or its affiliated companies
//
// SPDX-License-Identifier: MPL-2.0

// Example sketch using Arduino_LED_Matrix and RouterBridge. This sketch
// exposes five providers:
//  - "draw"            — receives pixel data and renders it on the matrix
//  - "load_frame"      — appends one frame to the animation buffer
//  - "play_animation"  — starts sequential playback of buffered frames
//  - "stop_animation"  — halts any running animation
//  - "write_sentence"  — spells out a Hebrew sentence using letter frames from Animation.h

#include <Arduino_RouterBridge.h>
#include <Arduino_LED_Matrix.h>
#include <vector>
#include <string.h>
#include <zephyr/kernel.h>
#include "Animation.h"

Arduino_LED_Matrix matrix;

// Bridge providers run on a separate thread from loop().
// This mutex protects shared animation state and serializes LED matrix writes.
K_MUTEX_DEFINE(anim_mtx);

// Animation playback state
static const int MAX_FRAMES = 300;
static uint32_t animation_buf[MAX_FRAMES][5]; // 4 words + duration (ms)
static int animation_frame_count = 0;
static bool animation_running = false;
static int animation_current_frame = 0;
static unsigned long animation_next_time = 0;

// --- Hebrew letter frames (from Animation.h) ---------------------------------
//
// Hebrew letters are encoded in UTF-8 as a fixed 2-byte sequence: lead byte
// 0xD7 followed by a continuation byte in [0x90..0xAA], one value per
// codepoint in the Unicode block U+05D0 (Alef) .. U+05EA (Tav).
// hebrewLetterToFrame[continuationByte - 0x90] gives the index into
// animation[][5] that draws that letter, or -1 if that letter has no frame
// yet. Both animation[][5] and hebrewLetterToFrame[] are defined in
// Animation.h, regenerated by the web UI's "Upload Alphabet" feature.
static const size_t ANIMATION_FRAME_COUNT = sizeof(animation) / sizeof(animation[0]);

// --- Scrolling text state -----------------------------------------------------
//
// write_sentence() renders the whole sentence into a wide off-screen canvas
// (scrollBuf), then scroll_tick() slides a 13-column window across it,
// decrementing scrollWindowStart each step so the content moves to the RIGHT:
// it enters at the left edge (col 0) and exits at the right edge (col 12).
static const int SCROLL_MAX_COLS = 800; // ~57 letters at 14 cols each, plenty of headroom
static uint8_t scrollBuf[8][SCROLL_MAX_COLS]; // 0 or 7 (on/off) per pixel
static int scrollWidth = 0;
static int scrollWindowStart = 0;
static bool scrollActive = false;
static unsigned long scrollNextTime = 0;
static const uint32_t SCROLL_STEP_MS = 120; // ms per column shift — lower = faster scroll

void setup() {
  matrix.begin();
  // Configure grayscale bits to 3 so the display accepts 0..7 brightness.
  // The backend sends quantized values in 0..(2^3-1) == 0..7.
  matrix.setGrayscaleBits(3);
  matrix.clear();

  Bridge.begin();
  Bridge.provide("draw", draw);
  Bridge.provide("load_frame", load_frame);
  Bridge.provide("play_animation", play_animation);
  Bridge.provide("stop_animation", stop_animation);
  Bridge.provide("write_sentence", write_sentence);

  // Uncomment to play a fixed sentence at boot, no Python/Web UI needed:
  // write_sentence("שלום");
}

void loop() {
  // Keep loop fast and let animation_tick/scroll_tick handle playback timing
  animation_tick();
  scroll_tick();
}

// --- Bridge providers --------------------------------------------------------

void draw(std::vector<uint8_t> frame) {
  if (frame.empty()) return;

  k_mutex_lock(&anim_mtx, K_FOREVER);
  matrix.draw(frame.data());
  k_mutex_unlock(&anim_mtx);
}

void load_frame(std::array<uint32_t, 5> data) {
  if (data.empty()) return;

  k_mutex_lock(&anim_mtx, K_FOREVER);

  if (animation_frame_count >= MAX_FRAMES) {
    k_mutex_unlock(&anim_mtx);
    return;
  }

  int idx = animation_frame_count++;
  animation_buf[idx][0] = data[0];
  animation_buf[idx][1] = data[1];
  animation_buf[idx][2] = data[2];
  animation_buf[idx][3] = data[3];
  animation_buf[idx][4] = data[4];

  k_mutex_unlock(&anim_mtx);
}

void play_animation() {
  k_mutex_lock(&anim_mtx, K_FOREVER);
  animation_current_frame = 0;
  animation_running = true;
  animation_next_time = millis();
  k_mutex_unlock(&anim_mtx);
}

void stop_animation() {
  k_mutex_lock(&anim_mtx, K_FOREVER);
  animation_running = false;
  animation_frame_count = 0;
  animation_current_frame = 0;
  scrollActive = false;
  k_mutex_unlock(&anim_mtx);
}

// Each drawn letter fills its full 13-column frame, but the glyph itself
// (typically only 6-7 columns wide) sits somewhere inside that frame with
// blank padding around it. Advancing the scroll by the full 13 columns per
// letter made the gap between letters look much bigger than GAP_WIDTH.
// frameGlyphLeft/RightCol[] cache each frame's actual lit-pixel column
// range so we can advance (and copy) only the glyph's real width.
static int8_t frameGlyphLeftCol[MAX_FRAMES];
static int8_t frameGlyphRightCol[MAX_FRAMES];
static bool frameGlyphBoundsReady = false;

static void computeFrameGlyphBounds() {
  for (size_t f = 0; f < ANIMATION_FRAME_COUNT; f++) {
    const uint32_t* words = animation[f];
    int left = -1, right = -1;
    for (int row = 0; row < 8; row++) {
      for (int col = 0; col < 13; col++) {
        int j = row * 13 + col;
        uint8_t bit = (words[j / 32] >> (31 - (j % 32))) & 1;
        if (bit) {
          if (left == -1 || col < left) left = col;
          if (col > right) right = col;
        }
      }
    }
    if (left == -1) {
      // Fully blank frame: fall back to the whole 13-column width.
      left = 0;
      right = 12;
    }
    frameGlyphLeftCol[f] = left;
    frameGlyphRightCol[f] = right;
  }
  frameGlyphBoundsReady = true;
}

// Trimmed on-screen width of a letter: the real glyph span for a drawn
// frame, or the full 13-column placeholder width for an undrawn letter
// (frameIdx < 0) so it still reserves visible blank space in the sentence.
static int letterVisualWidth(int frameIdx) {
  if (frameIdx < 0 || (size_t)frameIdx >= ANIMATION_FRAME_COUNT) return 13;
  return frameGlyphRightCol[frameIdx] - frameGlyphLeftCol[frameIdx] + 1;
}

// Decodes animation[frameIdx] (a 128-bit row-major 8x13 bitmask, see
// Animation.h / app_frame.py's to_animation_hex) into scrollBuf, placing
// only the glyph's trimmed columns at [startCol, startCol+letterVisualWidth).
static void decodeLetterIntoScroll(int frameIdx, int startCol) {
  const uint32_t* words = animation[frameIdx]; // words[0..3]; words[4] (duration) unused here
  int left = frameGlyphLeftCol[frameIdx];
  int right = frameGlyphRightCol[frameIdx];
  for (int row = 0; row < 8; row++) {
    for (int col = left; col <= right; col++) {
      int destCol = startCol + (col - left);
      if (destCol < 0 || destCol >= SCROLL_MAX_COLS) continue;
      int j = row * 13 + col; // 0..103
      uint8_t bit = (words[j / 32] >> (31 - (j % 32))) & 1;
      scrollBuf[row][destCol] = bit ? 7 : 0;
    }
  }
}

// Renders `text` into scrollBuf (skipping letters with no drawn frame, e.g.
// Alef, but still leaving their column width as blank space) and starts the
// right-moving scroll via scroll_tick(). A space renders as a smaller gap.
//
// scroll_tick() moves content to the right by decreasing scrollWindowStart,
// which means whatever sits at the HIGH-column end of the buffer is the
// leading edge and enters (and is seen) first — like the front car of a
// train moving right. To have the sentence read in the order it was typed
// (first letter first), we lay it out mirrored: the first character typed
// goes at the high-column/leading end, the last character at the low end.
void write_sentence(String text) {
  k_mutex_lock(&anim_mtx, K_FOREVER);

  if (!frameGlyphBoundsReady) computeFrameGlyphBounds();

  // Stop any frame-based animation that might be running.
  animation_running = false;
  animation_frame_count = 0;
  animation_current_frame = 0;
  scrollActive = false;
  memset(scrollBuf, 0, sizeof(scrollBuf));

  const int GAP_WIDTH = 1;    // blank columns between two letters of the same word
  const int SPACE_WIDTH = 3;  // additional blank columns for a space char (on top of the
                               // previous letter's own GAP_WIDTH), so word breaks total 4

  // Pass 1: compute the total width so we know where the leading (high) end is.
  int width = 0;
  {
    const uint8_t* p = reinterpret_cast<const uint8_t*>(text.c_str());
    while (*p && width < SCROLL_MAX_COLS) {
      if (p[0] == 0xD7 && p[1] >= 0x90 && p[1] <= 0xAA) {
        int letterIdx = p[1] - 0x90;
        int frameIdx = hebrewLetterToFrame[letterIdx];
        width += letterVisualWidth(frameIdx) + GAP_WIDTH;
        p += 2;
      } else if (p[0] == ' ') {
        width += SPACE_WIDTH;
        p += 1;
      } else {
        p += 1;
      }
    }
  }

  // Pass 2: place each letter mirrored around `width` (first-typed -> leading/high end).
  int col = 0;
  const uint8_t* p = reinterpret_cast<const uint8_t*>(text.c_str());
  while (*p && col < width) {
    if (p[0] == 0xD7 && p[1] >= 0x90 && p[1] <= 0xAA) {
      int letterIdx = p[1] - 0x90;
      int frameIdx = hebrewLetterToFrame[letterIdx];
      int letterWidth = letterVisualWidth(frameIdx);
      int startCol = width - col - letterWidth;
      if (frameIdx >= 0 && (size_t)frameIdx < ANIMATION_FRAME_COUNT) {
        decodeLetterIntoScroll(frameIdx, startCol);
      }
      col += letterWidth + GAP_WIDTH;
      p += 2;
    } else if (p[0] == ' ') {
      col += SPACE_WIDTH;
      p += 1;
    } else {
      // Skip unsupported bytes (punctuation, other scripts, stray UTF-8 continuation bytes).
      p += 1;
    }
  }

  scrollWidth = width;
  if (scrollWidth > 0) {
    scrollWindowStart = scrollWidth; // fully off-screen; about to enter from the left
    scrollActive = true;
    scrollNextTime = millis();
  }

  k_mutex_unlock(&anim_mtx);
}

// --- Animation engine --------------------------------------------------------

void animation_tick() {
  k_mutex_lock(&anim_mtx, K_FOREVER);

  if (!animation_running || animation_frame_count == 0) {
    k_mutex_unlock(&anim_mtx);
    return;
  }

  unsigned long now = millis();
  if (now < animation_next_time) {
    k_mutex_unlock(&anim_mtx);
    return;
  }

  int cur = animation_current_frame;

  // Prepare frame words (reverse bits as the library expects)
  uint32_t frame[4];
  frame[0] = reverse(animation_buf[cur][0]);
  frame[1] = reverse(animation_buf[cur][1]);
  frame[2] = reverse(animation_buf[cur][2]);
  frame[3] = reverse(animation_buf[cur][3]);

  // Schedule next frame
  uint32_t interval = animation_buf[cur][4];
  if (interval == 0) interval = 1;
  animation_next_time = now + interval;

  animation_current_frame++;
  if (animation_current_frame >= animation_frame_count) {
    animation_running = false;
    animation_frame_count = 0;
    animation_current_frame = 0;
  }

  // Display frame while still under lock to prevent draw() interference
  matrixWrite(frame);

  k_mutex_unlock(&anim_mtx);
}

// Slides a 13-column window across scrollBuf, one column per SCROLL_STEP_MS,
// decrementing scrollWindowStart so the text moves to the right (enters at
// col 0, exits at col 12). Stops once the whole buffer has scrolled past.
void scroll_tick() {
  k_mutex_lock(&anim_mtx, K_FOREVER);

  if (!scrollActive) {
    k_mutex_unlock(&anim_mtx);
    return;
  }

  unsigned long now = millis();
  if (now < scrollNextTime) {
    k_mutex_unlock(&anim_mtx);
    return;
  }

  uint8_t frame[104];
  for (int row = 0; row < 8; row++) {
    for (int c = 0; c < 13; c++) {
      int srcCol = scrollWindowStart + c;
      frame[row * 13 + c] = (srcCol >= 0 && srcCol < scrollWidth) ? scrollBuf[row][srcCol] : 0;
    }
  }
  matrix.draw(frame);

  scrollWindowStart--;
  scrollNextTime = now + SCROLL_STEP_MS;

  if (scrollWindowStart < -13) {
    scrollActive = false;
    matrix.clear();
  }

  k_mutex_unlock(&anim_mtx);
}
